############ Master Branch ############
-
  branches:
    only:     
      - master      
  version: '1.0.{build}'
  image: Visual Studio 2017
  skip_commits:
    files:
      - README.md  
  init:
    # Good practice, because Windows line endings are different from Linux ones
    - cmd: git config --global core.autocrlf true
  # Test against the latest version of this Node.js version
  environment:
    nodejs_version: "8.11.1"  
    
    websiteName: weatherforecastdev01
    artifactName: weatherforecastdev01
    
  # Install scripts. (runs after repo cloning)
  install:
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node $env:nodejs_version
    # install modules    
    - npm install
    - npm install -g @angular/cli@6.0.0 
  # build Configuration, i.e. Debug, Release, etc.
  configuration: Debug      
  build_script:
    - ng build
  # to run tests  
  test: off  
  after_build:
   # for once the build has completed
  artifacts:
    - path: '\dist'
      name: $(artifactName)
      type: WebDeployPackage    
   
  clone_depth: 1
  on_finish:
    # any cleanup in here
  deploy:
    - provider: WebDeploy
      server: https://%websiteName%.scm.azurewebsites.net:443/msdeploy.axd?site=%websiteName%
      website: $(websiteName)
      username: bsbhandari      
      password: bhandari90
      app_offline: true
      NTLM: disabled
      artifact: $(artifactName)
  
  notifications:
  - provider: Email  
    to:
    
    - mbhakuni@rythmos.com       
    message: "<div style=\"font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;\">\n   {{#passed}} \n   <h1 style=\"font-size: 150%;font-weight:normal; color:#078DC7;\"><a href=\"{{buildUrl}}\" style=\"color:#078DC7;\">Build {{projectName}} {{buildVersion}} completed</a></h1>\n\n<ul>\n      {{#jobs}}    \n      <li><p> For details build log <a href=\"https://ci.appveyor.com/api/buildjobs/{{id}}/log\">click here</a></p></li>   \n      {{/jobs}}\n   </ul> \n\n   {{/passed}} {{#failed}} \n   <h1 style=\"font-size: 150%;font-weight:normal; color:#ff3228;\"><a href=\"{{buildUrl}}\" style=\"color:#ff3228;\">Build {{projectName}} {{buildVersion}} failed</a></h1>\n   <p>Build messages:</p>\n   <ul>\n      {{#jobs}}\n      {{#messages}}\n      <li>{{message}}</li>\n      {{/messages}}\n      {{/jobs}}\n   </ul>\n   {{/failed}} \n   <p style=\"color: #888;\"> Commit <a href=\"{{commitUrl}}\">{{commitId}}</a> by <a href=\"mailto:{{commitAuthorEmail}}\">{{commitAuthor}}</a> on {{commitDate}}: <br /> <span style=\"font-size: 110%;color:#222;\">{{commitMessage}}</span> </p>\n\n<p>Build messages:</p>\n   <ul>\n      {{#jobs}}\n      {{#messages}}\n      <li>{{message}}</li>\n      {{/messages}}\n      {{/jobs}}\n   </ul>\n\n<p>Appveyor log messages:</p>\n\n<table border=\"1\">\n{{#jobs}}\n<tr>\n<th>Category</th>\n<th>Message</th>\n<th>Details</th>\n<th>ProjectFileName</th>\n<th>FileName</th>\n<th>Line</th>\n<th>Column</th>\n\n</tr>\n{{#compilationMessages}}\n<tr>\n<td>{{category}}</td>\n<td>{{message}}</td>\n<td>{{details}}</td>\n<td>{{projectFileName}}</td>\n<td>{{fileName}}</td>\n<td>{{line}}</td>\n<td>{{column}}</td>\n</tr>\n{{/compilationMessages}}\n{{/jobs}}\n<tablel>\n\n</div>"
    
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  
  
      
  
   



  
              
  
  
      
        
                           
                       
